export const amazonSiteUrlMapping: Record<string, string> = {
  "amazon.com": "https://www.amazon.com/",
  "amazon.co.uk": "https://www.amazon.co.uk/",
  "amazon.de": "https://www.amazon.de/",
  "amazon.com.au": "https://www.amazon.com.au/",
  "amazon.it": "https://www.amazon.it/",
  "amazon.ca": "https://www.amazon.ca/",
  "amazon.es": "https://www.amazon.es/",
  "amazon.fr": "https://www.amazon.fr/",
  "amazon.com.hk": "https://www.amazon.com/", // fallback, no official Amazon HK
  "amazon.sg": "https://www.amazon.sg/",
  "amazon.pl": "https://www.amazon.pl/",
  "amazon.nl": "https://www.amazon.nl/",
};
export const MARKETPLACE_TO_COUNTRY: Record<string, string> = {
  "amazon.com": "US",
  "amazon.co.uk": "UK",
  "amazon.de": "DE",
  "amazon.fr": "FR",
  "amazon.it": "IT",
  "amazon.es": "ES",
  "amazon.ca": "CA",
  "amazon.co.jp": "JP",
  "www.amazon.com": "US",
  "www.amazon.co.uk": "UK",
  "www.amazon.de": "DE",
  "www.amazon.fr": "FR",
  "www.amazon.it": "IT",
  "www.amazon.es": "ES",
  "www.amazon.ca": "CA",
  "www.amazon.co.jp": "JP",
};
export const MARKETPLACE_TO_CURRENCY_ISO_4217 : Record<string, string> = {
  "amazon.com": "USD",
  "amazon.co.uk": "GBP",
  "amazon.de": "EUR",
  "amazon.fr": "EUR",
  "amazon.it": "EUR",
  "amazon.es": "EUR",
  "amazon.ca": "CAD",
  "amazon.co.jp": "JPY",
  "amazon.com.mx": "MXN",
  "amazon.com.br": "BRL",
  "amazon.in": "INR",
  "amazon.com.au": "AUD",
  "amazon.nl": "EUR",
  "amazon.se": "SEK",
  "amazon.sg": "SGD",
  "amazon.com.tr": "TRY",
  "amazon.ae": "AED",
  "amazon.sa": "SAR",
  "www.amazon.com": "USD",
  "www.amazon.co.uk": "GBP",
  "www.amazon.de": "EUR",
  "www.amazon.fr": "EUR",
  "www.amazon.it": "EUR",
  "www.amazon.es": "EUR",
  "www.amazon.ca": "CAD",
  "www.amazon.co.jp": "JPY",
  "www.amazon.com.mx": "MXN",
  "www.amazon.com.br": "BRL",
  "www.amazon.in": "INR",
  "www.amazon.com.au": "AUD",
  "www.amazon.nl": "EUR",
  "www.amazon.se": "SEK",
  "www.amazon.sg": "SGD",
  "www.amazon.com.tr": "TRY",
  "www.amazon.ae": "AED",
  "www.amazon.sa": "SAR",
};

export const MARKETPLACE_TO_LANGUAGE_LOCALE_CODE : Record<string, string> = {
  "amazon.com": "en_US",
  "amazon.co.uk": "en_GB",
  "amazon.de": "de_DE",
  "amazon.fr": "fr_FR",
  "amazon.it": "it_IT",
  "amazon.es": "es_ES",
  "amazon.ca": "en_CA",
  "amazon.co.jp": "ja_JP",
  "amazon.com.mx": "es_MX",
  "amazon.com.br": "pt_BR",
  "amazon.in": "en_IN",
  "amazon.com.au": "en_AU",
  "amazon.nl": "nl_NL",
  "amazon.se": "sv_SE",
  "amazon.sg": "en_SG",
  "amazon.com.tr": "tr_TR",
  "amazon.ae": "en_AE",
  "amazon.sa": "ar_SA",
  "www.amazon.com": "en_US",
  "www.amazon.co.uk": "en_GB",
  "www.amazon.de": "de_DE",
  "www.amazon.fr": "fr_FR",
  "www.amazon.it": "it_IT",
  "www.amazon.es": "es_ES",
  "www.amazon.ca": "en_CA",
  "www.amazon.co.jp": "ja_JP",
  "www.amazon.com.mx": "es_MX",
  "www.amazon.com.br": "pt_BR",
  "www.amazon.in": "en_IN",
  "www.amazon.com.au": "en_AU",
  "www.amazon.nl": "nl_NL",
  "www.amazon.se": "sv_SE",
  "www.amazon.sg": "en_SG",
  "www.amazon.com.tr": "tr_TR",
  "www.amazon.ae": "en_AE",
  "www.amazon.sa": "ar_SA",
};

export const amazonDefualtSiteToEbaySiteMapping: Record<string, string> = {
  "amazon.com": "https://www.ebay.com/",
  "amazon.co.uk": "https://www.ebay.co.uk/",
  "amazon.de": "https://www.ebay.de/",
  "amazon.com.au": "https://www.ebay.com.au/",
  "amazon.it": "https://www.ebay.it/",
  "amazon.ca": "https://www.ebay.ca/",
  "amazon.es": "https://www.ebay.es/",
  "amazon.fr": "https://www.ebay.fr/",
  "amazon.com.hk": "https://www.ebay.com.hk/", // fallback, no official Amazon HK
  "amazon.sg": "https://www.ebay.com.sg/",
  "amazon.pl": "https://www.ebay.pl/",
  "amazon.nl": "https://www.ebay.nl/",
};
